get   http://localhost:3005/Doctors
Content-Type: application/json

{
    "Doctor":"63f96cfc48002698bbe28d09",
    "Content":"mohamed",
    "Date":"hassan",
    "ArticleCommunication":"640d2dc3db8801119385c01a"

}
###
GET  http://localhost:3005/DoctorHomePage/63f96cfc48002698bbe28d09
###
DELETE   http://localhost:3005/Articles/644f215d825fb9a8e9505dd2
Content-Type: application/json

{
   "Doctor":"63f96cfc48002698bbe28d09",
   "Content":"mohamed",
   "Date":"moahmed",
   "ArticleTitle":"mohamed"
}
###
GET  http://localhost:3005/Articles/ HTTP/1.1
### create product
POST http://localhost:3005/Appointments
Content-Type: application/json

{
   
    "AppointmentDate": "Diaa",
    "AppointmentTime": "Hosney",
    "PateintRequest": "Hosney",
     "Doctor":"63f00000760946737c1b3856",
     "Patient":"64088ea123d4dfc194e82dfb"
    


}



### get a product by id
GET http://localhost:3005/Doctors

### update a product by id
PATCH  http://localhost:4000/products/63997efc6b22caf957d21e5
Content-Type: application/json

{
    
    "price":1799
}


### delete a product by id
DELETE http://localhost:4000/products/63997f6f6b22caf957d21e60





### 404 route not found
GET http://localhost:4000/nohfh

###
POST http://localhost:4000/test
Content-Type: application/json

{
    "name":"imacpro",
    "price":4999
}
