
### get Articles
Get https://test-third-baseline.onrender.com/Articles


### get home page by Doctor id
GET http://localhost:3005/DoctorHomePage/644720ec6b72f3ad6db85f19


### get Article communication by id
Get https://test-third-baseline.onrender.com/ArticleCommunication/articlecommunication/644722056b72f3ad6db85f24

### post article
Post https://test-third-baseline.onrender.com/Articles
Content-Type: application/json

{
   "Doctor":"63f96e9ba5312120267b9760",
   "Content":"hosney",
   "Date":"hosney",
   "ArticleTitle":"hosney"
}
### add comment
PATCH  https://test-third-baseline.onrender.com/ArticleCommunication/patchCommunicationComments/64446570332b391322ac06e3
Content-Type: application/json

{
    "Comments":[{"Doctor":"63f96da5eec1af9d1c7f2566"}]
}
### add likes
PATCH  https://test-third-baseline.onrender.com/ArticleCommunication/patchCommunicationLikes/64446570332b391322ac06e3
Content-Type: application/json

{
"Likes":[{"DoctorId":"63f96da5eec1af9d1c7f9999"}]
}