
### get Articles

POST  http://localhost:3007/Appointments/addPatientAppointment/645d0c802b62fe8bd38a5575
Content-Type: application/json

{
    "Patient":"6447230b6b72f3ad6db85f27",
    "Doctor":"644720ec6b72f3ad6db85f19",
    "AppointmentDate":"Wed Mar 03 2021 02:00:00 GMT+0200 (Eastern European Standard Time)",
    "AppointmentTime":"sunday",
    "PateintRequest":"Trust issues",
    "duration":"122"
}
###
     
POST  https://test-third-baseline.onrender.com/Appointments/addPatientAppointment/645d0c802b62fe8bd38a5575
Content-Type: application/json

{
    "Patient":"6447230b6b72f3ad6db85f27",
    "Doctor":"644720ec6b72f3ad6db85f19",
    "AppointmentDate":"2023-05-15 18:56:13.202111",
    "AppointmentTime":"12:00 am",
    "PateintRequest":"ahhhh ya doctorrrr",
    "duration":"30 m"
}

### get home page by Doctor id
GET http://localhost:3007/Appointments


###Patient Home Page
GET http://localhost:3007/PatientHomePage/6447230b6b72f3ad6db85f27


### get Article communication by id
DELETE  http://localhost:3005/ArticleCommunication/patchCommunicationComments/deleteComment/644722056b72f3ad6db85f24/6448ec8371465cf789552ebd

### post article
Post https://test-third-baseline.onrender.com/Articles
Content-Type: application/json

{
   "Doctor":"63f96e9ba5312120267b9760",
   "Content":"hosney",
   "Date":"hosney",
   "ArticleTitle":"hosney"
}
### add comment
PATCH  https://test-third-baseline.onrender.com/ArticleCommunication/patchCommunicationComments/64446570332b391322ac06e3
Content-Type: application/json

{
    "Comments":[{"Doctor":"63f96da5eec1af9d1c7f2566"}]
}
### add likes
Get http://localhost:3007/Patients



###
PATCH  http://localhost:3007/patientSchadule/patchSchadule/6447230b6b72f3ad6db85f27
Content-Type: application/json

{
    "Appointment":["644720ec6b72f3ad6db85f19"],
    "Pills":[{
        "Image": "diaa",
        "PillName": "diaa",
        "Number": "diaa",
        "FinishDate": "diaa",
        "HowToUse": "diaa"
       
      }],
    "Activities":[{
        "Name": "diaa",
        "Time": "diaa"
      
      }]
}
###
GET http://localhost:3007/patientSchadule/6447230b6b72f3ad6db85f27